# -*- coding: utf-8 -*-
"""sevDura.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_gZRvPrNDkK514eVzOxEgWdU9R3ccj6N
"""

date()
c_gsFilename_which <- c(
  " - 2023Nov16-0630", # includes `medication` & `triggerTravel`
  " - 2023Nov02-2015" # shared for 2023Nov03 review
)[1]
c_gsFilename <- paste0("nimHeadacheDiary", c_gsFilename_which, ".csv")
c_wt_severityMax <- c(1.00, 0.60, 0.70)[3]
  # ie (1 - c_wt_severityMax) is weight for durationH, as suggested by Anirudh
c_width <- c(7)[1] # aggregate days---e.g., 7 for a week---for rolling analysis

if(! require(zoo)){ install.packages(c("zoo")); require(zoo) }

c_sevDura_0nil_default <- c(NA_integer_, 0)[2] # or NA_real_
c_tryFormats <- c("%Y-%b-%d", "%Y-%m-%d")
create_sevDura_v2 <- function(dat, sevDura_0nil_default=c_sevDura_0nil_default){
  # added 2023Nov13
  wt_dur <- (max(dat$severityMax, na.rm=TRUE) /
    max(dat$durationH, na.rm=TRUE)) *
      (1 - c_wt_severityMax)
  dur_sevMax <- (dat$severityMax * c_wt_severityMax) + (dat$durationH * wt_dur)
  dur_sevMax[is.na(dur_sevMax)] <- sevDura_0nil_default # was: 0
    summary(dur_sevMax)
  # plot(dur_sevMax, type="l")
  sevDura <- zoo(x=dur_sevMax, order.by=dat$date)
  return(sevDura)
}
getHMfrac <- function(start24Hvec){
  start24H.h <- (start24Hvec %/% 100)
  start24H.m <- (start24Hvec - (start24H.h * 100)) / 60
  start24H.hm <- start24H.h + start24H.m
  return(start24H.hm)
}
myRead_headacheDiary_v2 <- function(fName=c_gsFilename, tryFormats=c_tryFormats,
  sevDura_0nil_default=c_sevDura_0nil_default){
  gsfData <- read.csv(file=fName) # avoid myReadSheet(c_gsFilename) coz might cache OAuth credentials
  # str(gsfData)
  dat <- gsfData
  dat$date <- as.Date(dat$date, tryFormats=tryFormats)
  dat$site <- as.factor(dat$site)
  # str(dat)
  dat$siteTemp <- gsfData$site
  hasTemporal <- grepl(pattern="Temporal.*", x=dat$siteTemp); str(which(hasTemporal))
  hasFrontal <- grepl(pattern="Frontal.*", x=dat$siteTemp); str(which(hasFrontal))
  dat$siteTemp[hasFrontal & (! hasTemporal)] <- "FrontalsnoTemporal"
  dat$siteTemp[hasTemporal] <- "Temporalplus"
  dat$siteTemp[(dat$siteTemp == "")] <- "0nil"
  dat$siteTemp <- as.factor(dat$siteTemp)
  dat$prescription <- as.factor(dat$prescription)
  dat$severityMax[(dat$siteTemp == "0nil") & is.na(dat$severityMax)] <- sevDura_0nil_default
  dat$durationH[(dat$siteTemp == "0nil") & is.na(dat$durationH)] <- sevDura_0nil_default
    # was till 2023Nov12: <- 0
  medication <- dat$medication
    medication[(medication == "")] <- "0nil"
    dat$medication_fac <- as.factor(medication)
    # dat$medication_fac <- addNA(dat$medication_fac, ifany=TRUE)
  triggerTravel <- sub(pattern="yes.*", replacement="yes", x=dat$triggerTravel)
    triggerTravel[(triggerTravel == "")] <- "0nil"
    dat$triggerTravel_fac <- as.factor(triggerTravel)
    # dat$triggerTravel_fac <- addNA(dat$triggerTravel_fac, ifany=TRUE)
  dat$start24HMfrac <- getHMfrac(dat$start24H)
  summary(dat)
  return(dat)
}

myFunc <- list(
  function(winVec, naAct=TRUE){ mean(winVec, na.rm=naAct) },
  function(winVec, naAct=TRUE){ median(winVec, na.rm=naAct) }
)[[1]]
  # alt: runmed(x, k, endrule = c("median", "keep", "constant")[1]) # for the 'most robust' scatter plot smoothing possible
myReadSheet <- function(gsFilename) {
  # ref https://stackoverflow.com/questions/59746036/how-to-read-data-from-google-drive-using-r-in-colab
  require(googlesheets4)
  require(googledrive)
  gs_file <- drive_get(gsFilename) # was: drive_get('name_of_sheet_on_google')
  gs_data <- read_sheet(gs_file)
  return(gs_data)
}
myRead <- function(fName=c_gsFilename){
  gsfData <- read.csv(file=fName) # avoid myReadSheet(c_gsFilename) coz might cache OAuth credentials
  # str(gsfData)
  dat <- gsfData
  dat$date <- as.Date(dat$date, tryFormats=c("%Y-%b-%d"))
  dat$site <- as.factor(dat$site)
  # str(dat)
  dat$siteTemp <- gsfData$site
  hasTemporal <- grepl(pattern="Temporal.*", x=dat$siteTemp); str(which(hasTemporal))
  hasFrontal <- grepl(pattern="Frontal.*", x=dat$siteTemp); str(which(hasFrontal))
  dat$siteTemp[hasFrontal & (! hasTemporal)] <- "FrontalsnoTemporal"
  dat$siteTemp[hasTemporal] <- "Temporalplus"
  dat$siteTemp[(dat$siteTemp == "")] <- "0nil"
  dat$siteTemp <- as.factor(dat$siteTemp)
  dat$prescription <- as.factor(dat$prescription)
  dat$severityMax[is.na(dat$severityMax) & (dat$siteTemp == "0nil")] <- 0
  dat$durationH[is.na(dat$durationH) & (dat$siteTemp == "0nil")] <- 0
  medication <- dat$medication
    medication[medication == ""] <- "0nil"
    dat$medication_fac <- as.factor(medication)
    # dat$medication_fac <- addNA(dat$medication_fac, ifany=TRUE)
  triggerTravel <- sub(pattern="yes.*", replacement="yes", x=dat$triggerTravel)
    triggerTravel[triggerTravel == ""] <- "0nil"
    dat$triggerTravel_fac <- as.factor(triggerTravel)
    # dat$triggerTravel_fac <- addNA(dat$triggerTravel_fac, ifany=TRUE)
  summary(dat)
  return(dat)
}
create_sevDura <- function(dat){
  wt_dur <- (max(dat$severityMax, na.rm=TRUE) /
    max(dat$durationH, na.rm=TRUE)) *
      (1 - c_wt_severityMax)
  dur_sevMax <- (dat$severityMax * c_wt_severityMax) + (dat$durationH * wt_dur)
  dur_sevMax[is.na(dur_sevMax)] <- 0; summary(dur_sevMax)
  # plot(dur_sevMax, type="l")
  sevDura <- zoo(x=dur_sevMax, order.by=dat$date)
  return(sevDura)
}

dat <- myRead_headacheDiary_v2() # was: myRead()
summary(dat)

plot(dat$severityMax, type="l")
sevMax_roll <- rollapply(dat$severityMax, width=c_width, FUN=myFunc, align="right")
plot(sevMax_roll, type="l")
summary(sevMax_roll)

plot(dat$durationH, type="l")
dur_roll <- rollapply(dat$durationH, width=c_width, FUN=myFunc, align="right")
plot(dur_roll, type="l")
summary(dur_roll)

plot(durationH ~ severityMax, data=dat)

cor.test(dat$durationH, dat$severityMax)

dat$sevDura <- create_sevDura_v2(dat)
plot(dat$sevDura, type="l")

hist(dat$severityMax)

hist(dat$durationH)

hist(dat$sevDura)

boxplot(sevDura ~ siteTemp, data=dat)

sevDura_roll <- rollapply(dat$sevDura, width=c_width, FUN=myFunc, align="right")
summary(sevDura_roll)
plot(sevDura_roll, type="l")

presc.summ <- lapply(levels(dat$prescription), FUN=function(presc)
  summary(na.exclude(coredata(dat$sevDura[dat$prescription == presc])))
)
names(presc.summ) <- levels(dat$prescription)
presc.summ.df <- cbind(round(do.call(rbind, presc.summ), 2),
  count=summary(dat$prescription))
colnames(presc.summ.df) <- c("Min", "Q1", "Median", "Mean", "Q3",	"Max",
  "CountWithNA")
presc.summ.df
USL <- round(presc.summ.df[rownames(presc.summ.df) == "1Ami25x001", "Median"] / (1 - 40/100), 2)

boxplot(sevDura ~ prescription, data=dat)
abline(h=USL, col="red", lty="dashed")

boxplot(start24H ~ prescription, data=dat)

boxplot(start24H ~ siteTemp, data=dat)
summary(dat$start24H)

boxplot(sevDura ~ triggerTravel_fac * medication_fac, data=dat)

## Bayesian Analysis
# `p_severityMax_exceedsThresh = p_severityMax_exceedsThresh_givenSOS * p_SOS /
#   p_SOS_given_severityMax_exceedsThresh`
# for Latex formulae, ref:
# https://colab.research.google.com/github/bebi103a/bebi103a.github.io/blob/master/lessons/00/intro_to_latex.ipynb#scrollTo=XoU5XDjs6lSO
thresh <- (1:7)[6]
n_severityMax_exceedsThresh_givenSOS <- nrow(dat[(! is.na(dat$severityMax)) &
  (dat$severityMax >= thresh) & (dat$medication_fac != "0nil"), ])
n_severityMax_exceedsThresh <- nrow(dat[(! is.na(dat$severityMax)) &
  (dat$severityMax >= thresh), ])
n_SOS <- nrow(dat[(dat$medication_fac != "0nil"), ])
n_dat <- nrow(dat)
n_myBayes <- c(n_severityMax_exceedsThresh_givenSOS, n_SOS, n_dat,
  n_severityMax_exceedsThresh)
names(n_myBayes) <- c("n_severityMax_exceedsThresh_givenSOS", "n_SOS", "n_dat",
  "n_severityMax_exceedsThresh"); n_myBayes

p_severityMax_exceedsThresh_givenSOS <-
  n_severityMax_exceedsThresh_givenSOS / n_SOS
p_SOS <- n_SOS / n_dat
p_SOS_given_severityMax_exceedsThresh <-
  n_severityMax_exceedsThresh_givenSOS / n_severityMax_exceedsThresh
p_severityMax_exceedsThresh <- p_severityMax_exceedsThresh_givenSOS * p_SOS /
  p_SOS_given_severityMax_exceedsThresh
p_myBayes <- c(p_severityMax_exceedsThresh_givenSOS, p_SOS,
  p_SOS_given_severityMax_exceedsThresh, p_severityMax_exceedsThresh)
names(p_myBayes) <- c("p_severityMax_exceedsThresh_givenSOS", "p_SOS",
  "p_SOS_given_severityMax_exceedsThresh", "p_severityMax_exceedsThresh")

date()
sessionInfo()

"""# What Really Matters in Future with a Migraine History

## Acknowledgment
Without (a) headache-diary data from Dr Vaijayanthy Kaushik and (b) treatment regimes offered by [NIMHANS](https://nimhans.ac.in/) Headache Clinic's Neurology Prof Dr Girish B. Kulkarni et al., this research viewpoint would not have been possible. Those treatment regimes also called for a headache diary to be maintained and reviewed. There's also a reviewer Anirudh who influenced the combining into a univariate response variable `sevDura`.

## Findings
Here are findings from a preliminary, exploratory analysis using a patient's [headache diary](https://docs.google.com/spreadsheets/d/1yZ1dzq_yoPYms7pENiPyIpXWY5po8IeSKFvzmkUmqyA/edit?usp=sharing):
1. `FrontalsnoTemporal`-site headaches occur on about 71% (=199/282) of the days. About 22% (=61/282) days have `0nil` headache.
2. `severityMax` exceeds 3 ---on a scale of 0--10--- on less than 1/4th of the days. Headaches sited `Temporalplus` (are fewer but) have significantly-worse `severityMax` than others.
3. A headache lasts about 4 hours `durationH`.
4. `start24H` is during 1100--1400 hours on about half the occasions when headache occurs, and about a quarter headaches start after 1400 hours. `start24H` seems to indicate earlier start of headaches as prescriptions progressed; refer boxplot. `Temporalplus`-site headaches start significantly earlier than `FrontalsnoTemporal` ones; refer boxplot. Patient revealed that the SOS process is influenced by `severityMax` and nearness to night-sleep time, in order to get a good night's rest.
5. Both the `severityMax` and `durationH` (rolling) time-series plots distinguish three regimes: pre, during, and post the `3Ami37*` prescription.
6. `severityMax & durationH`: it seems unsuitable for `durationH` to be weighted higher than severity; at most, it could be treated on par ie 0--10 scale of severity. Influenced by a reviewer, this weighted combination creates a univariate response variable `sevDura`.
7. Up to prescription `4Gab*`, there's better `sevDura` than subsequently; refer boxplot.
8. Amitryptiline was the prescription initially and around 2023-Apr during the least-adverse headaches. Considering its adverse bodily impact---e.g., drowsiness, constipation, and tremulousness---and that it might need to be continued lifelong, further prescription moved away from it. The patient had expressed that prescription `1Ami*` was "40% better than earlier." What's likely is that a central measure was being intuitively perceived. If so, it's likely that the pre-2023 median (or mean) for random variable `sevDura` is what's plotted as a dashed-horizontal line in red, viz., a tolerance upper-specification limit `USL`:
"""

USL

"""Here's a Bayesian Analysis. As per Bayes Theorem:
> $P(severityMax >= thresh) = \frac{P(severityMax >= thresh \mid SOS) \,
 P(SOS)}{P(SOS \mid severityMax >= thresh)}$

Considering sample probabilities involving SOS `medication` which interacts with `severityMax`, this yields the following unconditional estimate for $P(severityMax >= thresh)$ named as `p_severityMax_exceedsThresh`:
"""

cat(paste0("Where thresh=", thresh, ":"))
round(p_myBayes, 3)

"""## Way Forward
1. Boxplot shows `7Top*` prescription (present since 2023-Oct) with `sevDura` exceedances of `USL` about 1/4th the time. Motivate a possible result outcome: `sevDura` exceedances of `USL` tolerance shall be no more frequent than that of `1Ami*` and with lesser adversity than the evidenced `1Ami*, 3Ami*,` or `4Gab*` prescription regimes; this result may be within 2 months.
2. Accordingly if the `7Top*` prescription fails to cause the chosen result by 2023-Nov-24 (Friday), request the treatment-leading doctors to transition into a prescription between `1Ami25*` and `3Ami37*` whose efficacy for this patient has already been evidenced. There would be milder tremulousness, constipation would be eased by the present barley-water intake, and the milder drowsiness might be similar to what the patient often manages already during headaches. (This [author](mailto:yadevinit@gmail.com) believes there would be a device to break a tablet into small, equal fractions, if that's a concern.)
3. Also ask the doctors for any superior SOS process.
4. Through statistical analysis, further reveal any latent patterns hidden so far:
  - Attempt Survival Analysis to attribute the impact of prescription and other factors while controlling for the SOS-process impact. This could (a) include data on SOS-medicine intake `medication` and `triggerTravel` where travel was reported (as a headache trigger), (b) consider right-censored data since the SOS process is influenced by `severityMax` and nearness to night-sleep time, and (c) treat `start24H` in its proper `hh:mm` format, rather than as integer.
  - Reality seems to be the opposite of patient's belief that `start24H` is  delayed in recent times, e.g., during `Top*` prescription impacted by 21-day `*SPMF` till end-Oct. Maybe, timed restfulness or a new regime matters for (high-twitched) persons. Consider a Bayesian (prior) analysis.
  - Forecast `sevDura` using time-series stochastics or classification into robust sets. Using that, maybe alternative SOS prescription could be earlier and less toxic. Was there a rising trend with an overlaid oscillation since mid-2023? Could both `severityMax` and `durationH` be better represented as bi-modal distributions?
  - `sevDura` is a univariate-response variable in this research viewpoint. Consider the merits of an alternative multivariate-response analysis.
"""

write.csv(dat, file="dat.csv", row.names=FALSE)